### ISSUE TITLE
播放视频时没有声音

### ISSUE THREAD

**Issue by sunaliu** [snylonue/b2m#2]
## 状况描述

测试视频： <https://www.bilibili.com/video/BV1px411K7Zp> 等

使用 `b2m https://www.bilibili.com/video/BV1px411K7Zp` 播放时，视频没有声音，并且 MPV 有以下表现：

![image](https://user-images.githubusercontent.com/61548509/90153607-cad80900-ddbb-11ea-81da-c21d8d4e95d1.png)

进度条显示为视频长度的两倍少一点（该视频3分22秒），第二段“视频”无法缓冲或播放，右侧音轨显示为 `-/0` 也就是没有音轨。

猜测是 Dash 流格式分离视频和音频导致，不过找了半天这么远古的视频都翻出来了，就是找不到一个没有 Dash 流的视频，我也不知道怎么指定 `b2m` 使用原本的 flv，所以我也不能确定。

使用 `-j` 参数可以获得两个链接，不知道是不是我姿势不对，即使伪造了 `referrer` 头，这两个链接也会报`403`错误。`audio`字段给出了一个空数组`"audio":[]`。

## 系统信息

Debian 10.5 "buster"

一开始以为是 `you-get` 和 `mpv` 的版本旧了，还特别去更新了一下。`mpv` 不是 Debian Stable 仓库里的（仓库里的还在 0.29.1）。

执行 `b2m -c` 的结果如下

```
Running checking
b2m version: 0.19.0

Checking for you-get
Running you-get -V
you-get version: 0.4.1456,

Stdout:
Stderr:
you-get: version 0.4.1456, a tiny downloader that scrapes the web.

you-get checking succeeded

Checking for annie
Running annie -v
annie version: 0.10.3

Stdout:
annie: version 0.10.3, A fast, simple and clean video downloader.
Stderr:

annie checking succeeded

Checking for mpv
Running mpv -V
mpv version: 0.32.0

Stdout:
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 12 09:06:47 CET 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.2
Stderr:

mpv checking succeeded
```

**Comment by snylonue** [comment]
annie 0.10.3 改了输出的 json 的格式，crates.io 上的版本还没更新
可以从 git 仓库安装 (`cargo install --git https://github.com/snylonue/b2m.git`)
应该可以正常播放
![mpv-shot0075](https://user-images.githubusercontent.com/48825598/90219477-b71eb800-de38-11ea-91e6-6d2db2054e10.png)

另外目前会使用 annie 而不是 you-get 解析B站视频，也无法在运行时选择 (~~因为还没写~~)

**Comment by sunaliu** [comment]
换用 GitHub 上的版本可以了。

***

看 commit message 没看到修复于是也没读代码了，~~果然我还是懒啊~~

> 另外目前会使用 annie 而不是 you-get 解析B站视频，也无法在运行时选择 

不能在运行时选择 （✗）

想换解析器得改代码里面匹配顺序再编译运行 （✔）

**Comment by snylonue** [comment]
不用改代码，可以通过 `--no-default-features --features <NAME>` 选择
