### ISSUE TITLE
[Feature Request] 增加命令行参数使其接受传递给 MPV 的控制选项

### ISSUE THREAD

**Issue by MrAru** [snylonue/b2m#3]
有时我想开启 MPV 硬件加速, 需要开启 `--hwdec=auto` 选项; 或者想让 MPV 在视频缓冲后自动全屏播放, 需要添加 `--fs=yes` 选项. 上述两者虽然都可以在 MPV 界面初始化之后通过快捷键或者界面内的其他方式手动控制, 但终究不如有一个能通过 b2m 直接给 MPV 传递参数选项的方法来的方便直接. 因此是否可以在 b2m 中增加一个选项, 接受一个字符串, 并将其传递给 MPV 进行初始化? 例如:

```
USAGE:
    b2m [FLAGS] [OPTIONS] <url>

FLAGS:
    --no-option                 Don't pass any option to MPV
    
OPTIONS:
    -o, --option <options>      Set options passing to MPV
```

多个 options 之间可通过分号分割, 例如:

```
b2m -o "--hwdec=auto;--fs=yes" <url>
```

**Comment by snylonue** [comment]
[已经有这个功能了](https://github.com/snylonue/b2m/commit/f82dd1ceba18859a84bc121ae36adf15cc169002)，不过还没发 release
请试着从 github 安装 `cargo install --git https://github.com/snylonue/b2m.git`
用法和 `cargo run` 差不多 ` b2m [FLAGS] [OPTIONS] <url> [-- <mpv-args>...]` (例 `b2m https://www.bilibili.com/video/av417275323 -- --hwdec=cuda --mute=yes`)

**Comment by MrAru** [comment]
感谢回复! 我会等待新的 release 释出后再使用.

另外, 我想将本项目打包至 AUR (ArchLinux User Repo), 不知您意下如何.

**Comment by snylonue** [comment]
可以，不过因为学业原因可能没有时间维护

**Comment by MrAru** [comment]
十分感谢, 我已经将 b2m 打包至 AUR, 见 https://aur.archlinux.org/packages/b2m/ .

我会关闭该 issue.
