### ISSUE TITLE
Annie is getting renamed to Lux

### ISSUE THREAD

**Issue by hsghost** [snylonue/b2m#4]
`
Error caught with bilibili/annie
Error: Os {
    code: 2,
    kind: NotFound,
    message: "No such file or directory",
}
`

Please fix, thank you.

**Comment by snylonue** [comment]
wait for iawia002/lux#996 to be resolved

by the way, you can use `finata` as the backend by enabling feature `nfinata`[1], which is written in rust thus faster and more controlable.
[1] `cargo install b2m --all-features`

**Comment by snylonue** [comment]
try to install from the git repository
`cargo install b2m --git https://github.com/snylonue/b2m.git`

**Comment by snylonue** [comment]
0.25.0 is released and switched to lux

**Comment by hsghost** [comment]
@snylonue 

Still getting problems with both latest version of _b2m_ and _lux_ installations.

On _macOS 12.2_:
```
% b2m --version
b2m 0.25.0
% lux --version

lux: version v0.12.0, A fast and simple video downloader.

% b2m "https://www.bilibili.com/video/BV1YF411n737/"
Error: Invalid json data: Downloading https://www.bilibili.com/video/BV1YF411n737/ error:
json: unsupported type: func([]uint8) ([]uint8, error)
```

On _Ubuntu Desktop 21.10_:
```
$ b2m --version
b2m 0.25.0
$ lux --version

lux: version v0.12.0, A fast and simple video downloader.

$ b2m "https://www.bilibili.com/video/BV1xS4y1y7nW"
Error: Invalid json data: Downloading https://www.bilibili.com/video/BV1xS4y1y7nW error:
json: unsupported type: func([]uint8) ([]uint8, error)
```

While downloading these videos directly through _lux_ showed no problem. The issue should be on the _b2m_ end.

Also, _lux_ is currently having problems resolving some of the bangumi lists, and even some individual ep's. Do you think dropping _you-get_ support at this time really a good idea?

**Comment by snylonue** [comment]
@hsghost 

> Still getting problems with both latest version of b2m and lux installations.

You need to install the latest lux via `go install github.com/iawia002/lux@HEAD`.

```
 cargo run -- https://www.bilibili.com/video/BV1YF411n737/ --no-cookie -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target\debug\b2m.exe https://www.bilibili.com/video/BV1YF411n737/ --no-cookie -i`
[src\main.rs:24] res = Finata {
    raws: [
        Origin {
            tracks: [
                Video(https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/06/27/493502706/493502706-1-30064.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1643905562&gen=playurlv2&os=cosbv&oi=827715085&trid=e678663d20834d4a832a9a1f7c6b73b8u&platform=pc&upsig=50bb1e36549959ce3163970335a040f1&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=145150&logo=80000000),
                Audio(https://upos-sz-mirrorkodo.bilivideo.com/upgcxcode/06/27/493502706/493502706-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1643905562&gen=playurlv2&os=kodobv&oi=827715085&trid=e678663d20834d4a832a9a1f7c6b73b8u&platform=pc&upsig=b26c211ebe8be2a26a7bc24ad29988a9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=17056&logo=80000000),
            ],
            title: "",
        },
    ],
    title: "车打来详解 - 长效避孕药为什么会配有安慰剂",
}
```

> Also, lux is currently having problems resolving some of the bangumi lists, and even some individual ep's.

[finata](https://github.com/snylonue/finata) might have fixed them, you can enable it via `cargo install b2m --all-features`, or port it to lux.

> Do you think dropping you-get support at this time really a good idea?

I have not used you-get for a long time. I will re-add it when I need to use it.

Sorry for my poor English

**Comment by hsghost** [comment]
@snylonue OK it's good now. Yet, I feel it's better to mention these in your README. Users like me ain't familiar with such tools from day one, especially for those hidden switches.

Anyway, good work, thanks!
